modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPLv3"

[[mods]]
modId = "litematica_printer"
version = "1.0.2"
displayName = "Litematica-Printer for Forge"
authors="jensvh"
# The description text for the mod (multi line!) (#mandatory)
description= '''
Litematica-Printer for Forge
'''

[[dependencies.litematica_printer]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="CLIENT"

[[dependencies.litematica_printer]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="CLIENT"

[[dependencies.litematica_printer]]
modId="litematica"
mandatory=true
versionRange="[0.11.6,)"
ordering="BEFORE"
side="CLIENT"